pub const REACH_GOAL_FALLING: &str = "...........
.....AX....
...aaa.....
...#.......";

pub const FALL_ON_SPIKE: &str = "....X..
..aA...
.+#....
....++.";

pub const FALL_ON_SNAKE_BUG: &str = "...X.
......
.B....
.baA..
.bb...
..#...";

pub const TEST_LEVELS: [&str; 3] = [REACH_GOAL_FALLING, FALL_ON_SPIKE, FALL_ON_SNAKE_BUG];
